# serverless.yml
service: tesseract-engine

provider:
  name: aws
  region: us-east-1
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}

  ecr:
    images:
      latest:
        path: ./
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - {
            "Fn::Join":
              [
                "",
                ["arn:aws:s3:::us-east-1-tesseract-engine-data", "/*"],
              ],
          }   

functions:
  handler:
    name: tesseract-engine-${self:provider.stage}
    memorySize: 4096
    timeout: 900
    image:
      name: latest
